name: Web-Performance
'on':
  push:
    branches:
      - master
  pull_request:
jobs:
  hugo:
    name: Hugo
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2

      - name: Build Hugo example site with image
        run: |
          cd tests/exampleSiteWithImage/
          hugo --logLevel=info --baseURL= --themesDir=../../../

      - name: Upload Hugo example site with image
        uses: actions/upload-artifact@v4
        with:
          name: hugo-example-site-with-image
          path: tests/exampleSiteWithImage/public

      - name: Build Hugo example site with video
        run: |
          cd tests/exampleSiteWithVideo/
          hugo --logLevel=info --baseURL= --themesDir=../../../

      - name: Upload Hugo example site with video
        uses: actions/upload-artifact@v4
        with:
          name: hugo-example-site-with-video
          path: tests/exampleSiteWithVideo/public

  sitespeed:
    name: Sitespeed.io
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run sitespeed.io for example site with image
        run: |
          docker compose --file tests/exampleSiteWithImage/docker-compose.yml up --exit-code-from sitespeed

      - name: Upload sitespeed.io result for example site with image
        uses: actions/upload-artifact@v4
        with:
          name: sitespeed.io-example-site-with-image
          path: tests/exampleSiteWithImage/sitespeed-result

      - name: Run sitespeed.io for example site with video
        run: |
          docker compose --file tests/exampleSiteWithVideo/docker-compose.yml up --exit-code-from sitespeed

      - name: Upload sitespeed.io result for example site with video
        uses: actions/upload-artifact@v4
        with:
          name: sitespeed.io-example-site-with-video
          path: tests/exampleSiteWithVideo/sitespeed-result
